In [1]:
import numpy as np

#### 1. a) Using the list comprehension technique generate the NumPy array

In [2]:
A = np.array([i + j for i in [15, 16, 18, 19, 20, 21] for j in [0, 10, 20, 40, 50, 60]])
A = A.reshape(6, 6)
A

array([[15, 25, 35, 55, 65, 75],
       [16, 26, 36, 56, 66, 76],
       [18, 28, 38, 58, 68, 78],
       [19, 29, 39, 59, 69, 79],
       [20, 30, 40, 60, 70, 80],
       [21, 31, 41, 61, 71, 81]])

#### b) Extract a sub matrices of order 4 × 3 and 4 × 5 from the above matrix A and name them as B and C.

In [3]:
B=A[0:4,0:3]
print("Submatrix of order 4x3:\n",B)

Submatrix of order 4x3:
 [[15 25 35]
 [16 26 36]
 [18 28 38]
 [19 29 39]]


In [4]:
C=A[0:4,0:5]
print("Submatrix of order 4x5:\n",C)

Submatrix of order 4x5:
 [[15 25 35 55 65]
 [16 26 36 56 66]
 [18 28 38 58 68]
 [19 29 39 59 69]]


#### c. Extract the submatrix D =[[20,40,70],[15,35,65]]

In [5]:
D1=A[0::4,::2]
D=D1[::-1]
print("Submatrix D :\n",D)

Submatrix D :
 [[20 40 70]
 [15 35 65]]


#### d. Generate random integer matrices E3×3, F5×3 with entries between 10 and 60 and G a random matrix
containing 5 elements

In [6]:
E=np.random.randint(10,61,(3,3))
F=np.random.randint(10,61,(5,3))
G=np.random.randint(10,61,(5,))

print("Matrix E (3x3):\n", E)
print("Matrix F (5x3):\n", F)
print("Matrix G (5 elements):\n", G)


Matrix E (3x3):
 [[14 32 58]
 [57 50 30]
 [50 44 17]]
Matrix F (5x3):
 [[37 13 38]
 [18 48 48]
 [45 34 60]
 [27 51 57]
 [21 57 51]]
Matrix G (5 elements):
 [26 16 34 32 44]


#### e. Compute the matrix H = B(F^T)C +G. While evaluating the product use appropriate product such as matrix product and dot product wherever applicable.


In [7]:
F1=F.T
H=(B@F1)*C+G
H

array([[ 33176,  78766, 126909, 202157, 229169],
       [ 36794,  84880, 135538, 213392, 241208],
       [ 44558,  97792, 153630, 236672, 266060],
       [ 48704, 104590, 163093, 248717, 278873]])

#### f. Round the entries of H to two decimal points and then find the square root of these elements and store as HS

In [8]:
H_rounded = np.round(H, 2)
HS = np.sqrt(H_rounded)
HS

array([[182.14280112, 280.65281043, 356.24289467, 449.61872737,
        478.71599096],
       [191.81762171, 291.34172375, 368.15485872, 461.94371952,
        491.12931087],
       [211.08765952, 312.71712457, 391.95663025, 486.48946546,
        515.81004255],
       [220.68982759, 323.4037724 , 403.84774359, 498.71534967,
        528.08427358]])

#### g. Find the inverse of the matrix, eigenvalues and eigenvectors of the matrix E

In [9]:
det_e=np.linalg.det(E)
if det_e!=0:
    e_inv=np.linalg.inv(E)
    print('The inverse of matrix E: \n',e_inv)
else:
    print('Matrix E is singular and cannot be inverted.')

The inverse of matrix E: 
 [[-0.04321442  0.1846267  -0.1783744 ]
 [ 0.0488231  -0.2447591   0.26535491]
 [ 0.00073556  0.09047444 -0.10334682]]


In [10]:
eigenvalues, eigenvectors = np.linalg.eig(E)
print("\n Eigenvalues of matrix E:\n ",eigenvalues)  
print("\nEigenvectors of matrix E (columns correspond to eigenvalues):\n ",eigenvectors)  


 Eigenvalues of matrix E:
  [117.8854576  -34.18678159  -2.69867601]

Eigenvectors of matrix E (columns correspond to eigenvalues):
  [[-0.50901398 -0.80351855  0.57803961]
 [-0.66753864  0.38106721 -0.77338713]
 [-0.54341231  0.45732452  0.260274  ]]


#### h. Find the row-wise and column-wise sum and product of the elements of the matrix (ED')'F'
.

In [11]:
m25=((E@D.T).T)@F1
m25
print("Column-wise sum: \n", np.sum(m25,axis=0,dtype=np.float64))
print("Row-wise sum: \n", np.sum(m25,axis=1,dtype=np.float64))
print("Column-wise product: \n", np.prod(m25,axis=0,dtype=np.float64))
print("Row-wise product: \n", np.prod(m25,axis=1,dtype=np.float64))

Column-wise sum: 
 [ 803085. 1015680. 1256130. 1207650. 1158030.]
Row-wise sum: 
 [2898780. 2541795.]
Column-wise product: 
 [1.60630358e+11 2.56715352e+11 3.92866044e+11 3.62980138e+11
 3.33726822e+11]
Row-wise product: 
 [6.14722544e+28 3.19241098e+28]


#### i. Is the matrices E, F are broadcastable? If Yes, what is the shape of the resultant matrix? if no, why?


In [12]:
print(np.shape(E))
print(np.shape(F))
E@F

(3, 3)
(5, 3)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 3)

#### Broadcastability of Matrices E and F  
### Reason  
The matrices \( E \) and \( F \) are not broadcastable because their shapes are incompatible. Specifically:  
- Shape of \( E \): (3, 3)  
- Shape of \( F \): (5, 3)  

When comparing the dimensions:  
- The last dimension (3 from \( E \) and 3 from \( F \)) is compatible.  
- However, the second last dimension (3 from \( E \) and 5 from \( F \)) is not compatible.  

Since the sizes of the dimensions do not match and neither dimension is 1, broadcasting cannot #occur.  

### Result  
**Are \( E \) and \( F \) broadcastable?**: **No**

#### j. Provide the python command to generate a matrix of order 4x3x5x3 by reshaping the matrices C,E,F and adding them

In [13]:
print(np.shape(C))
print(np.shape(E))
print(np.shape(F))
RE_C=C.reshape(4,1,5,1)
RE_E=E.reshape(1,3,1,3)
RE_F=F.reshape(1,1,5,3)
result= RE_C + RE_E + RE_F
print('The shape of the resulting matrix is: ',result.shape)

(4, 5)
(3, 3)
(5, 3)
The shape of the resulting matrix is:  (4, 3, 5, 3)
