In [4]:
# 1D array construction
import numpy as np
a = np. array ([0 , 1, 2, 3])
print ('Array a =',a)
print ('Array a dimension = ',a. ndim )
print ('Array a shape = ',a. shape )
print ('Array a size ( total no.of elements ) = ',a. size )
print ('Array a data type = ',a. dtype )
print ('Array a length = ',len(a))

Array a = [0 1 2 3]
Array a dimension =  1
Array a shape =  (4,)
Array a size ( total no.of elements ) =  4
Array a data type =  int32
Array a length =  4


In [6]:
# 2D array construction
import numpy as np
a = np. array ([[0 , 1, 2, 3.1] ,[4 , 5, 6, 7]])
print ('Array a =',a)
print ('Array a dimension = ',a. ndim )
print ('Array a shape = ',a. shape )
print ('Array a size ( total no.of elements ) = ',a. size )
print ('Array a data type = ',a. dtype )
print ('Array a length = ',len(a)) # Returns the size of the first dimension

Array a = [[0.  1.  2.  3.1]
 [4.  5.  6.  7. ]]
Array a dimension =  2
Array a shape =  (2, 4)
Array a size ( total no.of elements ) =  8
Array a data type =  float64
Array a length =  2


In [7]:
import numpy as np
a = np. array ([[[0 , 1, 2, 3] ,[4 , 5, 6, 7]] ,[[8 , 9, 10,
11] ,[12 , 13, 14, 15]]])
print ('Array a =',a)
print ('Array a dimension = ',a. ndim )
print ('Array a shape = ',a. shape )
print ('Array a size ( total no.of elements ) = ',a. size )
print ('Array a data type = ',a. dtype )
print ('Array a length = ',len(a))

Array a = [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
Array a dimension =  3
Array a shape =  (2, 2, 4)
Array a size ( total no.of elements ) =  16
Array a data type =  int32
Array a length =  2


In [10]:

import numpy as np
a = np. array ([[1 , 2, 4], [5, 8, 7]] , dtype = 'float')
print (" Array created using passed list :\n", a)

# Creating array from tuple
b = np. array ((1 , 3, 2))
print ("\n Array created using passed tuple :\n", b)

 Array created using passed list :
 [[1. 2. 4.]
 [5. 8. 7.]]

 Array created using passed tuple :
 [1 3 2]


In [15]:
c = np. zeros ((3 , 4))
print ("\n An array initialized with all zeros :\n", c)
d = np. full ((3 , 3) , 6, dtype = 'complex')
print ("\n An array initialized with all 6s. The Array type is complex :\n", d)
e = np. random . random ((2 , 2))
print ("\n A random array :\n", e)


 An array initialized with all zeros :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 An array initialized with all 6s. The Array type is complex :
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

 A random array :
 [[0.22157571 0.90715007]
 [0.1770623  0.8700807 ]]


In [18]:
f = np. arange (0, 30, 5)
print ("\n A sequential array with steps of 5:\n", f)
g = np. linspace (0, 5, 10)
print ("\n A sequential array with 10 values between 0 and 5:\n", g)


 A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

 A sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [19]:
arr = np. array ([[1 , 2, 3, 4],[5, 2, 4, 2],[1, 2, 0, 1]])
newarr = arr. reshape (2, 2, 3)
print ("\n Original array :\n", arr)
print (" Reshaped array :\n", newarr )


 Original array :
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
 Reshaped array :
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [21]:
arr = np. array ([[1 , 2, 3], [4, 5, 6]])
flarr = arr. flatten ()
print ("\n Original array :\n", arr)
print (" Flattened array :\n", flarr )


 Original array :
 [[1 2 3]
 [4 5 6]]
 Flattened array :
 [1 2 3 4 5 6]


In [22]:
a = np. array ([1 , 2, 3])
print (a. dtype )
a = np. array ([1.0 , 2, 3])
print (a. dtype )
a = np. array ([1+1j, 2.0+2j, 3])
print (a. dtype )
a = np. array ([ True , False , False , True , False ])
print (a. dtype )
a = np. array ([ 'Vellore ', 'Chennai ', 'Vijayawada ', 'Delhi ', 'Bengaluru '])
print (a. dtype )

int32
float64
complex128
bool
<U11


In [23]:
a = np. arange (10)
print (a)
print (a [0]+ a [2])

[0 1 2 3 4 5 6 7 8 9]
2


In [24]:
arr = np. array ([[1 ,2 ,3 ,4 ,5] , [6 ,7 ,8 ,9 ,10]])
print (arr [1 ,2])

8


In [1]:
import numpy as np
a = np.random.rand(5 ,4)
a[1 ,1] # List the second row second element
# a[: ,2] # List all elements in the third column
# a[1 ,:] # List all element in the second row .
a[1] # Similar to above
# a [1:5] # List the elements from the second to fifth element .
#a[(2 ,3):(1 ,2)] # List the [a[2 ,1] , a [3 ,2]] elements

array([0.30231828, 0.70231558, 0.38997894, 0.19719002])

In [49]:
a[ -3: -1]
a[ -3:]
arr = np. array ([[1 ,2 ,3 ,4 ,5] , [6 ,7 ,8 ,9 ,10]])
print ('Last element from 2nd dim : ', arr [1, -1])

Last element from 2nd dim :  10


In [35]:
a = np. array ([[0 ,1 ,2 ,3 ,4 ,5] , [10 ,11 ,12 ,13 ,14 ,15] ,
[20 ,21 ,22 ,23 ,24 ,25] , [30 ,31 ,32 ,33 ,34 ,35] ,
[40 ,41 ,42 ,43 ,44 ,45] , [50 ,51 ,52 ,53 ,54 ,55]])

print (a)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [37]:
b = a[: ,2]. copy ()
b = np. array ([1 , 1, 1, 1, 1, 1])
print(b)

[1 1 1 1 1 1]


In [48]:
# Integer array indexing example
temp = [[0 , 1, 2, 3], [3, 2, 1, 0]]
print ("\n Elements at indices (0, 3) , (1, 2) , (2, 1) ,(3, 0) :\n", temp )
cond = a < 0.5 # cond is a boolean array
temp = a[ cond ]
print ("\n Elements less than 0.5:\n", temp )


 Elements at indices (0, 3) , (1, 2) , (2, 1) ,(3, 0) :
 [[0, 1, 2, 3], [3, 2, 1, 0]]

 Elements less than 0.5:
 [0]


In [39]:
import numpy as np
a = np. array ([1 , 2, 5, 3])
# add 1 to every element
print (" Adding 1 to every element :", a+1)
print (" Subtracting 3 from each element :", a -3)
print (" Multiplying each element by 10:", a *10)

 Adding 1 to every element : [2 3 6 4]
 Subtracting 3 from each element : [-2 -1  2  0]
 Multiplying each element by 10: [10 20 50 30]


In [47]:
a = np. array ([[1 , 2, 3], [3, 4, 5], [9, 6, 0]])
print (" Squaring each element :", a **2)
a*= 2
print (" Doubled each element of original array :", a)
print ("\n Original array :\n", a)
print (" Transpose of array :\n", a.T)

 Squaring each element : [[ 1  4  9]
 [ 9 16 25]
 [81 36  0]]
 Doubled each element of original array : [[ 2  4  6]
 [ 6  8 10]
 [18 12  0]]

 Original array :
 [[ 2  4  6]
 [ 6  8 10]
 [18 12  0]]
 Transpose of array :
 [[ 2  6 18]
 [ 4  8 12]
 [ 6 10  0]]


In [50]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [52]:
np.zeros((1,2))

array([[0., 0.]])

In [53]:
np.ones((1,2))

array([[1., 1.]])

In [54]:
np.random.random((5,5))

array([[0.68550738, 0.51909418, 0.16217391, 0.77176674, 0.41154145],
       [0.44283663, 0.36739753, 0.72431986, 0.39935132, 0.13978414],
       [0.67233459, 0.18934991, 0.70154525, 0.39610098, 0.34036845],
       [0.57729821, 0.00137868, 0.88755858, 0.89997176, 0.6000791 ],
       [0.26621738, 0.31127339, 0.76087459, 0.53443423, 0.17830196]])

In [66]:
np.empty((0))

array([], dtype=float64)

In [74]:
array=np.array([[1,2,3,4],[1,2,3,4]])
array
array.astype(type)
type(array)

numpy.ndarray

In [79]:
other =array.copy()
other

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [3]:
import numpy as np

x=np.array([1,2,3])
y=np.array([1,1,1])
np.add(x,y)


array([2, 3, 4])

In [6]:
a=np.random.randint(1,10,20)
a=a.reshape(5,4)
a

array([[5, 3, 8, 9],
       [2, 7, 8, 7],
       [2, 7, 2, 2],
       [1, 6, 7, 5],
       [3, 9, 1, 8]])

In [7]:
a*2

array([[10,  6, 16, 18],
       [ 4, 14, 16, 14],
       [ 4, 14,  4,  4],
       [ 2, 12, 14, 10],
       [ 6, 18,  2, 16]])

In [8]:
a**2

array([[25,  9, 64, 81],
       [ 4, 49, 64, 49],
       [ 4, 49,  4,  4],
       [ 1, 36, 49, 25],
       [ 9, 81,  1, 64]])

In [9]:
a//2

array([[2, 1, 4, 4],
       [1, 3, 4, 3],
       [1, 3, 1, 1],
       [0, 3, 3, 2],
       [1, 4, 0, 4]], dtype=int32)

In [10]:
a-2

array([[ 3,  1,  6,  7],
       [ 0,  5,  6,  5],
       [ 0,  5,  0,  0],
       [-1,  4,  5,  3],
       [ 1,  7, -1,  6]])